/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2024-06-26 00:06:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.bean.Category;
import model.bean.CategoryGroup;
import model.bean.Brand;
import java.util.ArrayList;
import java.awt.Image;
import java.awt.Image;

public final class createProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1719328545819L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.bean.CategoryGroup");
    _jspx_imports_classes.add("model.bean.Brand");
    _jspx_imports_classes.add("java.awt.Image");
    _jspx_imports_classes.add("model.bean.Category");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write(" \r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"https://s3.ap-southeast-1.amazonaws.com/trihau.profile.image/logof.jpg\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/quill/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/quill/quill.bubble.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/simple-datatables/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("    \r\n");
      out.write("<body> \r\n");
      out.write("\r\n");

    HttpSession session = request.getSession();
    String fullname = "Guest"; // Giá trị mặc định
    String image = "default.png"; // Giá trị mặc định

    if (session != null) {
        if (session.getAttribute("fullname") != null) {
            fullname = (String) session.getAttribute("fullname");
        }
        if (session.getAttribute("image") != null) {
            image = (String) session.getAttribute("image");
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"header fixed-top d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("      <a href=\"ShowDashBoardServlet\" class=\"logo d-flex align-items-center\">\r\n");
      out.write("         <img src=\"https://s3.ap-southeast-1.amazonaws.com/trihau.profile.image/logo.jpg\" alt=\"\"> \r\n");
      out.write("        \r\n");
      out.write("      </a>\r\n");
      out.write("      <!-- <i class=\"bi bi-list toggle-sidebar-btn\"></i> -->\r\n");
      out.write("    </div><!-- End Logo -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- <div class=\"search-bar\">\r\n");
      out.write("      <form class=\"search-form d-flex align-items-center\" method=\"POST\" action=\"#\">\r\n");
      out.write("        <input type=\"text\" name=\"query\" placeholder=\"Search\" title=\"Enter search keyword\">\r\n");
      out.write("        <button type=\"submit\" title=\"Search\"><i class=\"bi bi-search\"></i></button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div> --><!-- End Search Bar -->\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"header-nav ms-auto\">\r\n");
      out.write("      <ul class=\"d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("        <!-- <li class=\"nav-item d-block d-lg-none\">\r\n");
      out.write("          <a class=\"nav-link nav-icon search-bar-toggle \" href=\"#\">\r\n");
      out.write("            <i class=\"bi bi-search\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li> --><!-- End Search Icon-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item dropdown pe-3\">\r\n");
      out.write("\r\n");
      out.write("          <a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("              <img src='");
      out.print(image);
      out.write("' alt=\"Profile\" class=\"rounded-circle\">\r\n");
      out.write("            <span class=\"d-none d-md-block dropdown-toggle ps-2\">");
      out.print(fullname);
      out.write("</span>\r\n");
      out.write("          </a><!-- End Profile Iamge Icon -->\r\n");
      out.write("\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("        </li><!-- End Profile Nav -->\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav><!-- End Icons Navigation -->\r\n");
      out.write("\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("  \r\n");
      out.write("<!--   <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a> -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write(" <script src=\"assets/vendor/apexcharts/apexcharts.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/chart.js/chart.umd.js\"></script> \r\n");
      out.write("  <script src=\"assets/vendor/echarts/echarts.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/quill/quill.js\"></script> \r\n");
      out.write("  <script src=\"assets/vendor/simple-datatables/simple-datatables.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/tinymce/tinymce.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  <!-- Bootstrap JS and dependencies -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </body>\r\n");
      out.write("  </html> ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
ArrayList<CategoryGroup> catGroup = (ArrayList<CategoryGroup>)request.getAttribute("catGroup"); 
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
ArrayList<Brand> brandList = (ArrayList<Brand>)request.getAttribute("brandList"); 
      out.write('\r');
      out.write('\n');
 String error1 = request.getParameter("message"); 
      out.write("\r\n");
      out.write("                              	    ");
 if ("1".equals(error1)) { 
      out.write("<div id=\"thongbao\" class=\"custom-alert-red hidden\"></div>");
 } 
      out.write("\r\n");
      out.write("                              	    ");
 if ("2".equals(error1)) { 
      out.write("<div id=\"thongbao\" class=\"custom-alert-red hidden\"></div>");
 } 
      out.write("\r\n");
      out.write("                              	    ");
 if ("3".equals(error1)) { 
      out.write("<div id=\"thongbao\" class=\"custom-alert-red hidden\"></div>");
 } 
      out.write("\r\n");
      out.write("                              	    ");
 if ("4".equals(error1)) { 
      out.write("<div id=\"thongbao\" class=\"custom-alert-red hidden\"></div>");
 } 
      out.write("\r\n");
      out.write("                              	    ");
 if ("0".equals(error1)) { 
      out.write("<div id=\"thongbao\" class=\"custom-alert-red hidden\"></div>");
 } 
      out.write("\r\n");
      out.write("                              	    ");
 if ("6".equals(error1)) { 
      out.write("<div id=\"thongbao\" class=\"custom-alert-red hidden\"></div>");
 } 
      out.write("\r\n");
      out.write("                              	    \r\n");
      out.write("\r\n");
      out.write("  <main id=\"main\" class=\"main\">\r\n");
      out.write("\r\n");
      out.write("<section class=\"section\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-lg-10\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("              <h5 class=\"card-title\">Thêm sản phẩm</h5>\r\n");
      out.write("\r\n");
      out.write("              <!-- Multi Columns Form -->\r\n");
      out.write("              <form class=\"row g-3\" action=\"CreateProductServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                <div class=\"col-md-9\">\r\n");
      out.write("                  <label for=\"inputName5\" class=\"form-label\">Tên sản phẩm</label>\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" id=\"inputName5\" name=\"nameProduct\">\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                  <label for=\"inputBrand\" class=\"form-label\">Thương hiệu</label>\r\n");
      out.write("                  <select id=\"inputBrand\" class=\"form-select\" name=\"brand\">\r\n");
      out.write("                    <option value ='' selected>---Chọn---</option>\r\n");
      out.write("                    ");
for(Brand b : brandList){ 
      out.write("\r\n");
      out.write("                    <option value ='");
      out.print(b.getBrandID());
      out.write('\'');
      out.write('>');
      out.print(b.getBrandName());
      out.write("</option>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                  </select>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("					<label for=\"categoryGroupSelect\" class=\"form-label\">Nhóm danh mục</label>\r\n");
      out.write("					<select id=\"categoryGroupSelect\" class=\"form-select\" name=\"catGroup\">\r\n");
      out.write("				    <option selected>---Chọn---</option>\r\n");
      out.write("				    ");
for(CategoryGroup cg : catGroup){ 
      out.write("\r\n");
      out.write("				<option value='");
      out.print(cg.getCategoryGroupID() );
      out.write('\'');
      out.write('>');
      out.print(cg.getCategoryGroupName() );
      out.write("</option>\r\n");
      out.write("				");
} 
      out.write("\r\n");
      out.write("				    </select><br>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"col-md-6\">\r\n");
      out.write("				    <label for=\"categorySelect\" class=\"form-label\">Danh mục</label>\r\n");
      out.write("				    <select id=\"categorySelect\" class=\"form-select\" name=\"cat\">\r\n");
      out.write("				        <option selected>---Chọn---</option>\r\n");
      out.write("				        <!-- Options sẽ được cập nhật bởi AJAX -->\r\n");
      out.write("				    </select>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("              \r\n");
      out.write("                \r\n");
      out.write("                <div id=\"divAttribute\" class=\"row\" >\r\n");
      out.write("	                <div id=\"productAttribute0\"  class=\"row\">\r\n");
      out.write("		                 <div class=\"col-md-3\">\r\n");
      out.write("		                  <label for=\"inputDungtich\" class=\"form-label\">Dung tích</label>\r\n");
      out.write("		                  <input type=\"text\" class=\"form-control\" name=\"size\">\r\n");
      out.write("		                </div>\r\n");
      out.write("		                \r\n");
      out.write("		                 <div class=\"col-md-3\">\r\n");
      out.write("		                  <label for=\"inputPrice\" class=\"form-label\">Giá</label>\r\n");
      out.write("		                  <input type=\"text\" class=\"form-control\" name='price'>\r\n");
      out.write("		                </div>\r\n");
      out.write("						<div class=\"col-md-3\">\r\n");
      out.write("						  <label for=\"inputQuantity\" class=\"form-label\">Số lượng</label>\r\n");
      out.write("						  <input type=\"text\" class=\"form-control\" name=\"quantity\">\r\n");
      out.write("						</div>\r\n");
      out.write("							<div class=\"col-md-2\">\r\n");
      out.write("							        <label for=\"inputImage\" class=\"form-label\">Ảnh</label><br>\r\n");
      out.write("							        <img id=\"myimage\" src=\"\" alt=\"Image\" width='100' height='100' align=\"middle\" border='1px' /><br>\r\n");
      out.write("							        <label class=\"upload-label\" class=\"d-flex justify-content-center align-items-center\">\r\n");
      out.write("							          <input type=\"file\" class=\"inputImage\" id=\"inputImage\" accept=\"image/jpeg, image/png\" name=\"file\" size=\"60\"/>\r\n");
      out.write("							          <a><i style=\"color: blue\" class=\"bi bi-upload\"></i></a>\r\n");
      out.write("							</label>\r\n");
      out.write("							\r\n");
      out.write("							<label class=\"remove-label\" class=\"d-flex justify-content-center align-items-center\">\r\n");
      out.write("							  <a style=\"color: red\" class=\"removeImage\" href=\"#\"><i class=\"bi bi-trash\"></i></a>\r\n");
      out.write("							  </label>\r\n");
      out.write("							</div>	                 	               \r\n");
      out.write("                	</div>\r\n");
      out.write("                </div>\r\n");
      out.write("              <div >\r\n");
      out.write("                	<div class=\"col-md-2\" >\r\n");
      out.write("	 						 <button  class=\"btn btn-primary\" type=\"button\" onclick=\"addAttribute()\">Thêm</button>  \r\n");
      out.write("	 				  	</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                  <div class=\"col-12\">\r\n");
      out.write("                  	<label for=\"inputAddress5\" class=\"form-label\">Mô tả</label>\r\n");
      out.write("                    <textarea class=\"form-control\" style=\"height: 100px\" name='des'></textarea>\r\n");
      out.write("			    </div>\r\n");
      out.write("               \r\n");
      out.write("              \r\n");
      out.write("                <div class=\"text-center\">\r\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-primary\">Lưu</button>\r\n");
      out.write("                  <button type=\"reset\" class=\"btn btn-secondary\">Hủy</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </form><!-- End Multi Columns Form -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("    <script>\r\n");
      out.write("document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("    const showAlertMessage = (message) => {\r\n");
      out.write("        const alertElement = document.getElementById('thongbao');\r\n");
      out.write("        alertElement.textContent = message;\r\n");
      out.write("        alertElement.classList.remove('hidden');\r\n");
      out.write("        alertElement.classList.add('show');\r\n");
      out.write("\r\n");
      out.write("        setTimeout(() => {\r\n");
      out.write("            alertElement.classList.remove('show');\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                alertElement.classList.add('hidden');\r\n");
      out.write("            }, 500); // Thời gian khớp với thời gian của transition\r\n");
      out.write("        }, 1500); // Hiển thị thông báo trong 1,5 giây\r\n");
      out.write("    };\r\n");
      out.write("    ");
 if ("0".equals(error1)) { 
      out.write("showAlertMessage('Lỗi ko xác định!');");
 } 
      out.write("\r\n");
      out.write("    ");
 if ("1".equals(error1)) { 
      out.write("showAlertMessage('Lỗi trùng khóa');");
 } 
      out.write("\r\n");
      out.write("    ");
 if ("2".equals(error1)) { 
      out.write("showAlertMessage('Thiếu thông tin!');");
 } 
      out.write("\r\n");
      out.write("    ");
 if ("3".equals(error1)) { 
      out.write("showAlertMessage('Thiếu thông tin sản phẩm');");
 } 
      out.write("\r\n");
      out.write("    ");
 if ("4".equals(error1)) { 
      out.write("showAlertMessage('Giá sản phẩm không hợp lệ');");
 } 
      out.write("\r\n");
      out.write("    ");
 if ("6".equals(error1)) { 
      out.write("showAlertMessage('Số lượng sản phẩm không hợp lệ');");
 } 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("  <script>\r\n");
      out.write("  	\r\n");
      out.write("\r\n");
      out.write("  /* 	function addAttribute(){\r\n");
      out.write("  	    allDivDetails = $(\"[id^='productAttribute']\");\r\n");
      out.write("  	    divDetailsCount = allDivDetails.length;\r\n");
      out.write("  	    console.log(\"divDetailsCount: \" + divDetailsCount);\r\n");
      out.write("\r\n");
      out.write("  	    htmlDetailSection = `\r\n");
      out.write("  	        <div id=\"productAttribute");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divDetailsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"row\">\r\n");
      out.write("  	            <div class=\"col-md-4\">\r\n");
      out.write("  	                <label for=\"inputDungtich\" class=\"form-label\">Dung tích</label>\r\n");
      out.write("  	                <input type=\"text\" class=\"form-control\" name=\"dungtich\">\r\n");
      out.write("  	            </div>\r\n");
      out.write("  	            <div class=\"col-md-4\">\r\n");
      out.write("  	                <label for=\"inputPrice\" class=\"form-label\">Giá</label>\r\n");
      out.write("  	                <input type=\"text\" class=\"form-control\" name=\"price\">\r\n");
      out.write("  	            </div>\r\n");
      out.write("  	            <div class=\"col-sm-1\">\r\n");
      out.write("  	          <br>\r\n");
      out.write("  	                <a  class=\"btn btn-danger\" \r\n");
      out.write("  	                   href=\"javascript:removeDetailSectionById('productAttribute");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divDetailsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" \r\n");
      out.write("  	                   title=\"Xóa thuộc tính này\">Xóa</a>\r\n");
      out.write("  	            </div>\r\n");
      out.write("  	        </div>\r\n");
      out.write("  	    `;\r\n");
      out.write("\r\n");
      out.write("  	    $(\"#divAttribute\").append(htmlDetailSection);\r\n");
      out.write("  	}\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  	function removeDetailSectionById(id) {\r\n");
      out.write("  		$(\"#\" + id).remove();\r\n");
      out.write("  	} */\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <!-- <script >\n");
      out.write("  function addAttribute(){\r\n");
      out.write("	    allDivDetails = $(\"[id^='productAttribute']\");\r\n");
      out.write("	    divDetailsCount = allDivDetails.length;\r\n");
      out.write("	    console.log(\"divDetailsCount: \" + divDetailsCount);\r\n");
      out.write("\r\n");
      out.write("	    htmlDetailSection = `\r\n");
      out.write("	        <div id=\"productAttribute");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divDetailsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"row\">\r\n");
      out.write("	            <div class=\"col-md-4\">\r\n");
      out.write("	                <label for=\"inputDungtich\" class=\"form-label\">Dung tích</label>\r\n");
      out.write("	                <input type=\"text\" class=\"form-control\" name=\"dungtich\">\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <div class=\"col-md-4\">\r\n");
      out.write("	                <label for=\"inputPrice\" class=\"form-label\">Giá</label>\r\n");
      out.write("	                <input type=\"text\" class=\"form-control\" name=\"price\">\r\n");
      out.write("	            </div>\r\n");
      out.write("	            \r\n");
      out.write("	            \r\n");
      out.write("	            \r\n");
      out.write("	            <div class=\"col-md-3\">  \r\n");
      out.write("            	<label for=\"inputPrice\" class=\"form-label\">Ảnh</label><br>\r\n");
      out.write("			\r\n");
      out.write("				<img id=\"myimage\" src=\"\" alt=\"Image\" width='100' height='100' align=\"middle\" border='1px' /><br>\r\n");
      out.write("				<label for=\"inputImage\" class=\"upload-label\" class=\"d-flex justify-content-center align-items-center\">\r\n");
      out.write("                        <input type=\"file\" id=\"inputImage\" accept=\"image/jpeg, image/png\" name=\"file\"  size=\"60\"/>\r\n");
      out.write("                        <input name =\"imgOrigin\" id=\"modalLink\" type =\"hidden\"/>\r\n");
      out.write("                        <a><i style=\"color: blue\" class=\"bi bi-upload\"></i></a>\r\n");
      out.write("           		 </label>\r\n");
      out.write("            	<label class=\"remove-label\" class=\"d-flex justify-content-center align-items-center\">\r\n");
      out.write("                        <a style=\"color: red\" id=\"removeImage\" href=\"#\" ><i class=\"bi bi-trash\"></i></a>\r\n");
      out.write("            	</label>\r\n");
      out.write("            \r\n");
      out.write("       		 </div>\r\n");
      out.write("	            \r\n");
      out.write("	            \r\n");
      out.write("	            <div class=\"col-sm-1\">\r\n");
      out.write("	          <br>\r\n");
      out.write("	                <a  class=\"btn btn-danger\" \r\n");
      out.write("	                   href=\"javascript:removeDetailSectionById('productAttribute");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divDetailsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" \r\n");
      out.write("	                   title=\"Xóa thuộc tính này\">Xóa</a>\r\n");
      out.write("	            </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	    `;\r\n");
      out.write("\r\n");
      out.write("	    $(\"#divAttribute\").append(htmlDetailSection);\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	function removeDetailSectionById(id) {\r\n");
      out.write("		$(\"#\" + id).remove();\r\n");
      out.write("	}\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $(\"#inputImage\").change(function() {\r\n");
      out.write("            showImage(this);\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $(\"#removeImage\").click(function() {\r\n");
      out.write("            resetImage();\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function showImage(fileInput) {\r\n");
      out.write("        const file = fileInput.files[0];\r\n");
      out.write("        const reader = new FileReader();\r\n");
      out.write("        reader.onload = function(e) {\r\n");
      out.write("            $(\"#myimage\").attr(\"src\", e.target.result);\r\n");
      out.write("        };\r\n");
      out.write("        reader.readAsDataURL(file);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function resetImage() {\r\n");
      out.write("        // Sử dụng đường dẫn mặc định hoặc thực hiện các hành động cần thiết để reset ảnh\r\n");
      out.write("        $(\"#myimage\").attr(\"src\", \"\");\r\n");
      out.write("        // Xóa giá trị của input file\r\n");
      out.write("        $(\"#inputImage\").val('');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("	</script>   -->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("  function addAttribute() {\r\n");
      out.write("    const allDivDetails = $(\"[id^='productAttribute']\");\r\n");
      out.write("    const divDetailsCount = allDivDetails.length;\r\n");
      out.write("    console.log(\"divDetailsCount: \" + divDetailsCount);\r\n");
      out.write("\r\n");
      out.write("    const htmlDetailSection = `\r\n");
      out.write("      <div id=\"productAttribute");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divDetailsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"row\">\r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <label for=\"inputDungtich\" class=\"form-label\">Dung tích</label>\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" name=\"size\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <label for=\"inputPrice\" class=\"form-label\">Giá</label>\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" name=\"price\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-3\">\r\n");
      out.write("          <label for=\"inputQuantity\" class=\"form-label\">Số lượng</label>\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" name=\"quantity\">\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-2\">\r\n");
      out.write("          <label for=\"inputImage");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divDetailsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-label\">Ảnh</label><br>\r\n");
      out.write("          <img id=\"myimage");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divDetailsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" src=\"\" alt=\"Image\" width='100' height='100' align=\"middle\" border='1px' /><br>\r\n");
      out.write("          <label class=\"upload-label class=\"d-flex justify-content-center align-items-center\">\r\n");
      out.write("            <input type=\"file\" class=\"inputImage\" id=\"inputImage");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divDetailsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" accept=\"image/jpeg, image/png\" name=\"file\" size=\"60\"/>\r\n");
      out.write("            <a><i style=\"color: blue\" class=\"bi bi-upload\"></i></a>\r\n");
      out.write("          </label>\r\n");
      out.write("          <label class=\"remove-label\" class=\"d-flex justify-content-center align-items-center\">\r\n");
      out.write("            <a style=\"color: red\" class=\"removeImage\" href=\"#\"><i class=\"bi bi-trash\"></i></a>\r\n");
      out.write("          </label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-1\">\r\n");
      out.write("          <br>\r\n");
      out.write("          <a class=\"btn btn-danger\" href=\"javascript:removeDetailSectionById('productAttribute");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${divDetailsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" title=\"Xóa thuộc tính này\">Xóa</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    `;\r\n");
      out.write("\r\n");
      out.write("    $(\"#divAttribute\").append(htmlDetailSection);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function removeDetailSectionById(id) {\r\n");
      out.write("    $(\"#\" + id).remove();\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  $(document).ready(function() {\r\n");
      out.write("    // Event delegation for showing the image\r\n");
      out.write("    $(\"#divAttribute\").on(\"change\", \".inputImage\", function() {\r\n");
      out.write("      showImage(this);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    // Event delegation for removing the image\r\n");
      out.write("    $(\"#divAttribute\").on(\"click\", \".removeImage\", function(e) {\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      resetImage(this);\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  function showImage(fileInput) {\r\n");
      out.write("    const file = fileInput.files[0];\r\n");
      out.write("    const reader = new FileReader();\r\n");
      out.write("    reader.onload = function(e) {\r\n");
      out.write("      $(fileInput).closest('.row').find(\"img\").attr(\"src\", e.target.result);\r\n");
      out.write("    };\r\n");
      out.write("    reader.readAsDataURL(file);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  function resetImage(button) {\r\n");
      out.write("    const row = $(button).closest('.row');\r\n");
      out.write("    // Reset the image source\r\n");
      out.write("    row.find(\"img\").attr(\"src\", \"\");\r\n");
      out.write("    // Clear the file input value\r\n");
      out.write("    row.find(\".inputImage\").val('');\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("    $('#categoryGroupSelect').change(function() {\r\n");
      out.write("        var selectedCategoryGroupID = $(this).val();\r\n");
      out.write("        if (selectedCategoryGroupID !== '---Chọn---') {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: 'GetCategoriesByGroupServlet', \r\n");
      out.write("                type: 'GET',\r\n");
      out.write("                data: { categoryGroupID: selectedCategoryGroupID },\r\n");
      out.write("                success: function(response) {\r\n");
      out.write("                    console.log('Server response:', response); // in ra phản hồi từ server\r\n");
      out.write("                    try {\r\n");
      out.write("                        \r\n");
      out.write("                        var categories = response;\r\n");
      out.write("                        $('#categorySelect').empty();\r\n");
      out.write("                        $('#categorySelect').append('<option selected>---Chọn---</option>');\r\n");
      out.write("                        $.each(categories, function(index, category) {\r\n");
      out.write("                            $('#categorySelect').append(\r\n");
      out.write("                                $('<option>', {\r\n");
      out.write("                                    value: category.CategoryID.trim(), // loại bỏ khoảng trắng thừa\r\n");
      out.write("                                    text: category.CategoryName\r\n");
      out.write("                                })\r\n");
      out.write("                            );\r\n");
      out.write("                        });\r\n");
      out.write("                    } catch (e) {\r\n");
      out.write("                        console.error('Error processing response:', e);\r\n");
      out.write("                        console.log('Response that caused error:', response); // in ra phản hồi nếu lỗi xảy ra\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error: function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("                    console.log('Error fetching categories:', textStatus, errorThrown);\r\n");
      out.write("                    console.log('jqXHR:', jqXHR);\r\n");
      out.write("                    console.log('textStatus:', textStatus);\r\n");
      out.write("                    console.log('errorThrown:', errorThrown);\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        } else {\r\n");
      out.write("            $('#categorySelect').empty();\r\n");
      out.write("            $('#categorySelect').append('<option selected>---Chọn---</option>');\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
