/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2024-06-26 07:20:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.bean.Employee;
import model.bean.Category;
import java.util.ArrayList;
import java.awt.Image;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/sidebar.jsp", Long.valueOf(1718760777936L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1719328545819L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.awt.Image");
    _jspx_imports_classes.add("model.bean.Employee");
    _jspx_imports_classes.add("model.bean.Category");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Thông tin cá nhân</title>\r\n");
      out.write("  <link href=\"https://s3.ap-southeast-1.amazonaws.com/trihau.profile.image/logof.jpg\" rel=\"icon\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write(" \r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    <head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"https://s3.ap-southeast-1.amazonaws.com/trihau.profile.image/logof.jpg\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/quill/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/quill/quill.bubble.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"assets/vendor/simple-datatables/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("    \r\n");
      out.write("<body> \r\n");
      out.write("\r\n");

    HttpSession session = request.getSession();
    String fullname = "Guest"; // Giá trị mặc định
    String image = "default.png"; // Giá trị mặc định

    if (session != null) {
        if (session.getAttribute("fullname") != null) {
            fullname = (String) session.getAttribute("fullname");
        }
        if (session.getAttribute("image") != null) {
            image = (String) session.getAttribute("image");
        }
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Header ======= -->\r\n");
      out.write("  <header id=\"header\" class=\"header fixed-top d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex align-items-center justify-content-between\">\r\n");
      out.write("      <a href=\"ShowDashBoardServlet\" class=\"logo d-flex align-items-center\">\r\n");
      out.write("         <img src=\"https://s3.ap-southeast-1.amazonaws.com/trihau.profile.image/logo.jpg\" alt=\"\"> \r\n");
      out.write("        \r\n");
      out.write("      </a>\r\n");
      out.write("      <!-- <i class=\"bi bi-list toggle-sidebar-btn\"></i> -->\r\n");
      out.write("    </div><!-- End Logo -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- <div class=\"search-bar\">\r\n");
      out.write("      <form class=\"search-form d-flex align-items-center\" method=\"POST\" action=\"#\">\r\n");
      out.write("        <input type=\"text\" name=\"query\" placeholder=\"Search\" title=\"Enter search keyword\">\r\n");
      out.write("        <button type=\"submit\" title=\"Search\"><i class=\"bi bi-search\"></i></button>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div> --><!-- End Search Bar -->\r\n");
      out.write("\r\n");
      out.write("    <nav class=\"header-nav ms-auto\">\r\n");
      out.write("      <ul class=\"d-flex align-items-center\">\r\n");
      out.write("\r\n");
      out.write("        <!-- <li class=\"nav-item d-block d-lg-none\">\r\n");
      out.write("          <a class=\"nav-link nav-icon search-bar-toggle \" href=\"#\">\r\n");
      out.write("            <i class=\"bi bi-search\"></i>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li> --><!-- End Search Icon-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <li class=\"nav-item dropdown pe-3\">\r\n");
      out.write("\r\n");
      out.write("          <a class=\"nav-link nav-profile d-flex align-items-center pe-0\" href=\"#\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("              <img src='");
      out.print(image);
      out.write("' alt=\"Profile\" class=\"rounded-circle\">\r\n");
      out.write("            <span class=\"d-none d-md-block dropdown-toggle ps-2\">");
      out.print(fullname);
      out.write("</span>\r\n");
      out.write("          </a><!-- End Profile Iamge Icon -->\r\n");
      out.write("\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("        </li><!-- End Profile Nav -->\r\n");
      out.write("\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav><!-- End Icons Navigation -->\r\n");
      out.write("\r\n");
      out.write("  </header><!-- End Header -->\r\n");
      out.write("  \r\n");
      out.write("<!--   <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a> -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write(" <script src=\"assets/vendor/apexcharts/apexcharts.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/chart.js/chart.umd.js\"></script> \r\n");
      out.write("  <script src=\"assets/vendor/echarts/echarts.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/quill/quill.js\"></script> \r\n");
      out.write("  <script src=\"assets/vendor/simple-datatables/simple-datatables.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/tinymce/tinymce.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("  \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("  <!-- Bootstrap JS and dependencies -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  </body>\r\n");
      out.write("  </html> ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Vendor JS Files -->\r\n");
      out.write("\r\n");
      out.write("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ======= Sidebar ======= -->\r\n");
      out.write("  <aside id=\"sidebar\" class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("    <ul class=\"sidebar-nav\" id=\"sidebar-nav\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" <li class=\"nav-heading\">Cửa hàng</li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class='nav-link collapsed' href=\"ShowDashBoardServlet\">\r\n");
      out.write("          <i class=\"bi bi-grid\"></i>\r\n");
      out.write("          <span>Thống kê</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Dashboard Nav -->\r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("         <!-- <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" data-bs-target=\"#forms-nav\" data-bs-toggle=\"collapse\" href=\"ShowCategoryListServlet\">\r\n");
      out.write("          <i class=\"bi bi-journal-text\"></i><span>Danh mục</span><i class=\"bi bi-chevron-down ms-auto\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul id=\"forms-nav\" class=\"nav-content collapse \" data-bs-parent=\"#sidebar-nav\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a   href=\"ShowCategoryListServlet\" >\r\n");
      out.write("              <i  class=\"bi bi-circle\"></i><span>Quản lý danh mục</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"ShowCategoryGroupServlet\">\r\n");
      out.write("              <i class=\"bi bi-circle\"></i><span>Quản lý nhóm danh mục</span>\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("        \r\n");
      out.write("         \r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>     -->  <!-- End Danh mục Nav -->\r\n");
      out.write("       <!-- <li class=\"nav-item\">\r\n");
      out.write("        <a class='nav-link collapsed' href=\"ShowCategoryGroupServlet\">\r\n");
      out.write("          <i class=\"bi bi-menu-button-wide\"></i>\r\n");
      out.write("          <span>Nhóm danh mục</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li> --><!-- Sản phẩm Nav -->\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("       <li class=\"nav-item\">\r\n");
      out.write("        <a class='nav-link collapsed' href=\"ShowCategoryListServlet\">\r\n");
      out.write("          <i class=\"bi bi-menu-button-wide\"></i>\r\n");
      out.write("          <span>Danh mục</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- Sản phẩm Nav -->\r\n");
      out.write("      \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("         <li class=\"nav-item\">\r\n");
      out.write("        <a class='nav-link collapsed' href=\"ShowProductListServlet\">\r\n");
      out.write("          <i class=\"bi bi-menu-button-wide\"></i>\r\n");
      out.write("          <span>Sản phẩm</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- Sản phẩm Nav -->\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("        <a class='nav-link collapsed'  href=\"ShowCustomerListServlet\">\r\n");
      out.write("          <i class=\"bi bi-person\"></i>\r\n");
      out.write("          <span>Khách hàng</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- Khách hàng Nav -->\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class='nav-link collapsed'  href=\"ShowOrderListServlet\">\r\n");
      out.write("          <i class=\"bi bi-layout-text-window-reverse\"></i>\r\n");
      out.write("          <span>Đơn hàng</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- Đơn hàng Nav -->\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class='nav-link collapsed'  href=\"ShowEmployeeListServlet\">\r\n");
      out.write("          <i class=\"bi bi-person\"></i>\r\n");
      out.write("          <span>Nhân viên</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- Nhân viên Nav -->\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("       <li class=\"nav-item\">\r\n");
      out.write("        <a class='nav-link collapsed'  href=\"ShowBrandListServlet\">\r\n");
      out.write("          <i class=\"bi bi-gem\"></i>\r\n");
      out.write("          <span>Thương hiệu</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <li class=\"nav-heading\">Cá nhân</li>\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class='nav-link collapsed' href=\"ShowProfileServlet\">\r\n");
      out.write("          <i class=\"bi bi-person\"></i>\r\n");
      out.write("          <span>Thông tin cá nhân</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Profile Page Nav -->\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!--    <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"addEmployee.jsp\">\r\n");
      out.write("          <i class=\"bi bi-card-list\"></i>\r\n");
      out.write("          <span>Đăng ký tài khoản</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li>End Register Page Nav -->\r\n");
      out.write("\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link collapsed\" href=\"LogoutServlet\">\r\n");
      out.write("          <i class=\"bi bi-box-arrow-in-right\"></i>\r\n");
      out.write("          <span>Đăng xuất</span>\r\n");
      out.write("        </a>\r\n");
      out.write("      </li><!-- End Login Page Nav -->\r\n");
      out.write("\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("  </aside><!-- End Sidebar-->\r\n");
      out.write("  \r\n");
      out.write("     <!-- Vendor JS Files -->\r\n");
      out.write("  <!-- <script src=\"assets/vendor/apexcharts/apexcharts.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/chart.js/chart.umd.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/echarts/echarts.min.js\"></script>\r\n");
      out.write("  <script src=\"assets/vendor/quill/quill.js\"></script> \r\n");
      out.write(" <script src=\"assets/vendor/simple-datatables/simple-datatables.js\"></script>\r\n");
      out.write(" <script src=\"assets/vendor/tinymce/tinymce.min.js\"></script> \r\n");
      out.write("   -->\r\n");
      out.write("  <!-- Bootstrap JS and dependencies -->\r\n");
      out.write("<!-- <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>  -->\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write(" <script src=\"assets/js/main.js\"></script>  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
Employee profile = (Employee) request.getAttribute("profile"); 
      out.write('\r');
      out.write('\n');
String fileName = (String)request.getAttribute("fileName");
      out.write("\r\n");
      out.write("  <main id=\"main\" class=\"main\">\r\n");
      out.write(" ");
 String error = request.getParameter("message"); 
      out.write("\r\n");
      out.write("            		");
      out.print(("1".equals(error)) ?"Thay đổi mật khẩu thành công!" : "" );
      out.write("\r\n");
      out.write("            	   ");
      out.print(("2".equals(error)) ?"Lỗi thiếu thông tin các field bắt buộc nhập!" : "" );
      out.write("\r\n");
      out.write("            	   ");
      out.print(("3".equals(error))?"Mật khẩu cũ không đúng!":"" );
      out.write("\r\n");
      out.write("            	   ");
      out.print(("4".equals(error))?"Mật khẩu xác nhận và mật khẩu mới không trùng khớp!":"" );
      out.write("\r\n");
      out.write("            	   ");
      out.print(("5".equals(error))?"Lỗi không xác định!":"" );
      out.write("\r\n");
      out.write("            	   ");
      out.print(("6".equals(error))?"Mật khẩu dài ít nhất 8 kí tự, ít nhất 1 chữ hoa và 1 số!":"" );
      out.write("\r\n");
      out.write("            	   \r\n");
      out.write(" ");
 String error1 = request.getParameter("message1"); 
      out.write("\r\n");
      out.write("            		");
      out.print(("5".equals(error1)) ?"Thay đổi thông tin thành công!" : "" );
      out.write("\r\n");
      out.write("            	   ");
      out.print(("2".equals(error1)) ?"Lỗi thiếu thông tin bắt buộc nhập!" : "" );
      out.write("\r\n");
      out.write("            	   ");
      out.print(("4".equals(error1))?"Lỗi không xác định!":"" );
      out.write(" \r\n");
      out.write("            	   ");
      out.print(("10".equals(error1))?"Số điện thoại không hợp lệ!":"" );
      out.write(" \r\n");
      out.write("            	    \r\n");
      out.write("    <div class=\"pagetitle\">\r\n");
      out.write("      <h1>Thông tin cá nhân</h1>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <ol class=\"breadcrumb\">\r\n");
      out.write("          <li class=\"breadcrumb-item\"><a href=\"ShowDashBoardServlet\">Trang chủ</a></li>\r\n");
      out.write("          <li class=\"breadcrumb-item active\">Thông tin cá nhân</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div><!-- End Page Title -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section profile\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-xl-4\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body profile-card pt-4 d-flex flex-column align-items-center\">\r\n");
      out.write("\r\n");
      out.write("              <img src='");
      out.print(profile.getImage());
      out.write("' alt=\"Profile\" class=\"rounded-circle\">\r\n");
      out.write("              <h2>");
      out.print(profile.getFullName() );
      out.write("</h2>\r\n");
      out.write("              ");
if(("admin".equals(profile.getRole())) || ("admin1".equals(profile.getRole())) ) {
      out.write("\r\n");
      out.write("              <h3>Admin</h3>\r\n");
      out.write("              ");
}else { 
      out.write("\r\n");
      out.write("              <h3>Nhân viên</h3>\r\n");
      out.write("               ");
 } 
      out.write("\r\n");
      out.write("              <div class=\"social-links mt-2\">\r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-xl-8\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body pt-3\">\r\n");
      out.write("              <!-- Bordered Tabs -->\r\n");
      out.write("              <ul class=\"nav nav-tabs nav-tabs-bordered\">\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <button class=\"nav-link active\" data-bs-toggle=\"tab\" data-bs-target=\"#profile-overview\">Tổng quan</button>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <button class=\"nav-link\" data-bs-toggle=\"tab\" data-bs-target=\"#profile-edit\">Chỉnh sửa</button>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                  <button class=\"nav-link\" data-bs-toggle=\"tab\" data-bs-target=\"#profile-change-password\">Đổi mật khẩu</button>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("              </ul>\r\n");
      out.write("              <div class=\"tab-content pt-2\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"tab-pane fade show active profile-overview\" id=\"profile-overview\">\r\n");
      out.write("                  \r\n");
      out.write("                  <h5 class=\"card-title\">Thông tin cá nhân</h5>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 label \">Họ và tên</div>\r\n");
      out.write("                    <div class=\"col-lg-9 col-md-8\">");
      out.print(profile.getFullName() );
      out.write("</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("   					\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 label\">Địa chỉ</div>\r\n");
      out.write("                    <div class=\"col-lg-9 col-md-8\">");
      out.print(profile.getAddress());
      out.write("</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 label\">Số điện thoại</div>\r\n");
      out.write("                    <div class=\"col-lg-9 col-md-8\">");
      out.print(profile.getPhone() );
      out.write("</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-3 col-md-4 label\">Email</div>\r\n");
      out.write("                    <div class=\"col-lg-9 col-md-8\">");
      out.print(profile.getEmail() );
      out.write("</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("				<!-- Start edit div -->\r\n");
      out.write("                <div class=\"tab-pane fade profile-edit pt-3\" id=\"profile-edit\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- Profile Edit Form -->\r\n");
      out.write("          \r\n");
      out.write("            \r\n");
      out.write("               \r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"row mb-3\">\r\n");
      out.write("    				<label for=\"profileImage\" class=\"col-md-4 col-lg-3 col-form-label\">Ảnh</label>\r\n");
      out.write("    					<div class=\"col-md-8 col-lg-9 profile\">\r\n");
      out.write("       						 <img src='");
      out.print(profile.getImage());
      out.write("' alt=\"Image\"/><br>\r\n");
      out.write("       					 \r\n");
      out.write("        			<button type=\"button\" class=\"btn btn-primary btn-sm\" data-toggle=\"modal\" data-target=\"#uploadModal\">Thay đổi ảnh</button>\r\n");
      out.write("   					 </div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"uploadModal\" tabindex=\"-1\" aria-labelledby=\"uploadModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\" id=\"uploadModalLabel\">Thay đổi ảnh đại diện</h5>\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form action=\"FileUploadServlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                      \r\n");
      out.write("                            <div class=\"col-md-8 col-lg-9 profile\">\r\n");
      out.write("                                <img id=\"myimage\"  src='");
      out.print(profile.getImage());
      out.write("'  class='myImage123'/><br>\r\n");
      out.write("                                <input type = \"hidden\" name =\"imgOrigin\" value='");
      out.print(profile.getImage());
      out.write("'/>\r\n");
      out.write("                                <div class=\"upload-container\">\r\n");
      out.write("                                    <label for=\"inputImage\" class=\"upload-label\" class=\"d-flex justify-content-center align-items-center\">\r\n");
      out.write("                                        <input type=\"file\" id=\"inputImage\" accept=\"image/jpeg, image/png\" name=\"file\" size=\"60\" /> <!-- Ẩn input -->\r\n");
      out.write("                                        <span class=\"btn btn-primary btn-sm\" title=\"Upload new profile image\"><i class=\"bi bi-upload\"></i></span> <!-- Hiển thị nút upload -->\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    <label class=\"remove-label\"  class=\"d-flex justify-content-center align-items-center\">\r\n");
      out.write("                                        <a id=\"removeImage\" href=\"#\" class=\"btn btn-danger btn-sm\" title=\"Remove my profile image\"><i class=\"bi bi-trash\"></i></a> <!-- Move remove button here -->\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary btn-sm\">Lưu</button>\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary btn-sm\" data-dismiss=\"modal\">Hủy</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("              				  \r\n");
      out.write("   <form action=\"EditProfileServlet\" enctype=\"multipart/form-data\" >\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                      <label for=\"fullName\" class=\"col-md-4 col-lg-3 col-form-label\">Họ và tên</label>\r\n");
      out.write("                      <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                        <input name=\"fullName\" type=\"text\" class=\"form-control\" id=\"fullName\" value=\"");
      out.print(profile.getFullName() );
      out.write("\">\r\n");
      out.write("                        <input name=\"id\" type=\"hidden\" value=\"");
      out.print(profile.getEmployeeID());
      out.write("\">\r\n");
      out.write("                        <input name=\"username\" type=\"hidden\"  value=\"");
      out.print(profile.getUsername());
      out.write("\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("    		\r\n");
      out.write("    \r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                      <label for=\"Address\" class=\"col-md-4 col-lg-3 col-form-label\">Địa chỉ</label>\r\n");
      out.write("                      <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                        <input name=\"address\" type=\"text\" class=\"form-control\" id=\"Address\" value=\"");
      out.print(profile.getAddress() );
      out.write("\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                      <label for=\"Phone\" class=\"col-md-4 col-lg-3 col-form-label\">Số điện thoại</label>\r\n");
      out.write("                      <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                        <input name=\"phone\" type=\"text\" class=\"form-control\" id=\"Phone\" value=\"");
      out.print(profile.getPhone() );
      out.write("\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                      <label for=\"Email\" class=\"col-md-4 col-lg-3 col-form-label\">Email</label>\r\n");
      out.write("                      <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                        <input name=\"email\" type=\"email\" class=\"form-control\" id=\"Email\" value=\"");
      out.print(profile.getEmail() );
      out.write("\">\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-primary\">Lưu</button>\r\n");
      out.write("                      <button type=\"reset\" class=\"btn btn-secondary\">Hủy</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                   </form> \r\n");
      out.write("                 <!-- End Profile Edit Form -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"tab-pane fade pt-3\" id=\"profile-settings\">\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"tab-pane fade pt-3\" id=\"profile-change-password\">\r\n");
      out.write("                  <!-- Change Password Form -->\r\n");
      out.write("                  <form action = \"ChangePasswordServlet\" method =\"post\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                      <label for=\"currentPassword\" class=\"col-md-4 col-lg-3 col-form-label\">Mật khẩu cũ</label>\r\n");
      out.write("                      <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                      <div class=\"password-wrapper\">\r\n");
      out.write("                        <input name=\"pass\" type=\"password\" class=\"form-control\" id=\"password\">\r\n");
      out.write("                        <span class=\"toggle-password\" onclick=\"togglePasswordVisibility()\">👁️</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                      <label for=\"newPassword\" class=\"col-md-4 col-lg-3 col-form-label\">Mật khẩu mới</label>\r\n");
      out.write("                      <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                      <div class=\"password-wrapper\">\r\n");
      out.write("                        <input name=\"newpassword\" type=\"password\" class=\"form-control\" id=\"password2\">\r\n");
      out.write("                        <span class=\"toggle-password2\" onclick=\"togglePasswordVisibility2()\">👁️</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                      <label for=\"renewPassword\" class=\"col-md-4 col-lg-3 col-form-label\">Xác nhận mật khẩu</label>\r\n");
      out.write("                      <div class=\"col-md-8 col-lg-9\">\r\n");
      out.write("                      <div class=\"password-wrapper\">\r\n");
      out.write("                        <input name=\"renewpassword\" type=\"password\" class=\"form-control\" id=\"password3\">\r\n");
      out.write("                        <span class=\"toggle-password3\" onclick=\"togglePasswordVisibility3()\">👁️</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"text-center\">\r\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-primary\">Đổi mật khẩu</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form><!-- End Change Password Form -->\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div><!-- End Bordered Tabs -->\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script> \r\n");
      out.write("  <script src=\"assets/js/main.js\"></script>\r\n");
      out.write(" 	<script>\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        $(\"#inputImage\").change(function() {\r\n");
      out.write("            showImage(this);\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        $(\"#removeImage\").click(function() {\r\n");
      out.write("            resetImage();\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function showImage(fileInput) {\r\n");
      out.write("        const file = fileInput.files[0];\r\n");
      out.write("        const reader = new FileReader();\r\n");
      out.write("        reader.onload = function(e) {\r\n");
      out.write("            $(\"#myimage\").attr(\"src\", e.target.result);\r\n");
      out.write("        };\r\n");
      out.write("        reader.readAsDataURL(file);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function resetImage() {\r\n");
      out.write("        // Sử dụng đường dẫn mặc định hoặc thực hiện các hành động cần thiết để reset ảnh\r\n");
      out.write("        $(\"#myimage\").attr(\"src\", \"");
      out.print(profile.getImage());
      out.write("\");\r\n");
      out.write("        // Xóa giá trị của input file\r\n");
      out.write("        $(\"#inputImage\").val('');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("	</script>  \r\n");
      out.write(" <script>\r\n");
      out.write("        function togglePasswordVisibility() {\r\n");
      out.write("            const passwordInput = document.getElementById('password');\r\n");
      out.write("            const togglePassword = document.querySelector('.toggle-password');\r\n");
      out.write("            const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';\r\n");
      out.write("            passwordInput.setAttribute('type', type);\r\n");
      out.write("            togglePassword.textContent = type === 'password' ? '👁️' : '🙈';\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("     <script>\r\n");
      out.write("        function togglePasswordVisibility2() {\r\n");
      out.write("            const passwordInput = document.getElementById('password2');\r\n");
      out.write("            const togglePassword = document.querySelector('.toggle-password2');\r\n");
      out.write("            const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';\r\n");
      out.write("            passwordInput.setAttribute('type', type);\r\n");
      out.write("            togglePassword.textContent = type === 'password' ? '👁️' : '🙈';\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("     <script>\r\n");
      out.write("        function togglePasswordVisibility3() {\r\n");
      out.write("            const passwordInput = document.getElementById('password3');\r\n");
      out.write("            const togglePassword = document.querySelector('.toggle-password3');\r\n");
      out.write("            const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';\r\n");
      out.write("            passwordInput.setAttribute('type', type);\r\n");
      out.write("            togglePassword.textContent = type === 'password' ? '👁️' : '🙈';\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</html>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
