/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2024-06-27 04:19:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.dto.CartDTO;
import model.dto.CustomerDTO;
import java.util.ArrayList;
import common.StringCommon;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.dto.CartDTO");
    _jspx_imports_classes.add("common.StringCommon");
    _jspx_imports_classes.add("model.dto.CustomerDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Trang Thanh Toán</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".body-checkout {\r\n");
      out.write("    width: 85%;\r\n");
      out.write("    flex-direction: row;\r\n");
      out.write("    margin: 0px; \r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    flex-wrap: wrap;\r\n");
      out.write("    width: 85%;\r\n");
      out.write("    max-width: 1200px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    margin-top: 0; \r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write(".left{\r\n");
      out.write("text-align: left !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");

ArrayList<CartDTO> cartList = (ArrayList<CartDTO>) request.getAttribute("cartList");

      out.write('\r');
      out.write('\n');

CustomerDTO cusDetail = (CustomerDTO) request.getAttribute("cusDetail");

      out.write("\r\n");
      out.write("\r\n");
 String fullname = cusDetail.getFullname() != null ? cusDetail.getFullname() : request.getParameter("fullname"); 
      out.write('\r');
      out.write('\n');
 String phone = cusDetail.getPhone() != null ? cusDetail.getPhone() : request.getParameter("phone"); 
      out.write('\r');
      out.write('\n');
 String address = cusDetail.getAddress() != null ? cusDetail.getAddress() : request.getParameter("address"); 
      out.write('\r');
      out.write('\n');
 String email = cusDetail.getEmail() != null ? cusDetail.getEmail() : request.getParameter("email"); 
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"header-left\">\r\n");
      out.write("			<img src=\"logo.jpg\" alt=\"Logo\" class=\"logo\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"header-center\">\r\n");
      out.write("			<nav>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"ShowHomeServlet\">Trang chủ</a></li>\r\n");
      out.write("					<li><a href=\"ShowProductListServlet\">Sản phẩm</a></li>\r\n");
      out.write("					<li><a href=\"#\">Thương hiệu</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("			<div class=\"search-bar\">\r\n");
      out.write("				<input type=\"text\" class=\"search-input\" placeholder=\"Tìm kiếm...\">\r\n");
      out.write("\r\n");
      out.write("				<button>\r\n");
      out.write("					<i class=\"fa-solid fa-magnifying-glass\"></i>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"header-right\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"cart\">\r\n");
      out.write("				<a href=\"ShowCartServlet\"><i class=\"fa-solid fa-cart-shopping\"></i></a>\r\n");
      out.write("				<!--    <p>Giỏ hàng</p> -->\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");

			if (session.getAttribute("accountInfor") == null) {
			
      out.write("\r\n");
      out.write("			<div class=\"profile-dropdown account\">\r\n");
      out.write("				<a href=\"login.jsp\" title=\"Đăng nhập\"><i\r\n");
      out.write("					class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("				<!--      <p>Tài khoản</p> -->\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			} else {
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"profile-dropdown account\">\r\n");
      out.write("				<a href=\"#\" title=\"Tài khoản\"><i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("				<!--<p>Tài khoản</p> -->\r\n");
      out.write("				<div class=\"profile-dropdown-content\">\r\n");
      out.write("					<a href=\"#\"><i class=\"fa-regular fa-user\"></i>Thông tin tài\r\n");
      out.write("						khoản</a> <a href=\"#\"><i class=\"fa-solid fa-list-check\"></i>Quản\r\n");
      out.write("						lý đơn hàng</a> <a href=\"LogoutServlet\"><i\r\n");
      out.write("						class=\"fa-solid fa-arrow-right-from-bracket\"></i>Đăng xuất</a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			");

			}
			
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"sub-header\">\r\n");
      out.write("		<div class=\"breadcrumb\">\r\n");
      out.write("			<a href=\"#\">Trang chủ</a> / <span>Thanh toán</span>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"body-checkout\">\r\n");
      out.write("		<div class=\"progress-bar\">\r\n");
      out.write("			<div class=\"step active\">\r\n");
      out.write("				<div class=\"icon\">\r\n");
      out.write("					<i class=\"fa-solid fa-cart-shopping\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text\">Giỏ hàng</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"line active\"></div>\r\n");
      out.write("			<div class=\"step active\">\r\n");
      out.write("				<div class=\"icon\">\r\n");
      out.write("					<i class=\"fa-regular fa-credit-card\"></i></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text\">Thanh toán</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"line\"></div>\r\n");
      out.write("			<div class=\"step\">\r\n");
      out.write("				<div class=\"icon\">\r\n");
      out.write("					<i class=\"fa-regular fa-circle-check\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"text\">Hoàn thành</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<form class=\"container-checkout\" action=\"AuthorizePaymentServlet\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"checkout-form\">\r\n");
      out.write("\r\n");
      out.write("				<h2>THÔNG TIN THANH TOÁN</h2>\r\n");
      out.write("				");
 String error = request.getParameter("error"); 
      out.write("\r\n");
      out.write("				 ");
if("1".equals(error)){
      out.write(" <div class=\"central\"><p style=\"color: red; font-size: 18px\"> Lỗi thiếu thông tin! </p></div>");
} 
      out.write("\r\n");
      out.write("				 ");
if("2".equals(error)){
      out.write(" <div class=\"central\"><p style=\"color: red; font-size: 18px\"> Số điện thoại không hợp lệ! </p></div>");
} 
      out.write("\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<label for=\"lastName\">Họ và tên<span>*</span></label> <input\r\n");
      out.write("						type=\"text\" id=\"lastName\" name=\"fullname\"\r\n");
      out.write("						value=\"");
      out.print(fullname);
      out.write("\" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- <div class=\"form-inline\">\r\n");
      out.write("					<div class=\"form-group-sub\">\r\n");
      out.write("						<label for=\"city\">Tỉnh, thành <span>*</span></label> <select\r\n");
      out.write("							id=\"city\" name=\"province\" required>\r\n");
      out.write("							<option value=\"\">Chọn tỉnh thành</option>\r\n");
      out.write("							Thêm các tỉnh thành khác ở đây\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group-sub\">\r\n");
      out.write("						<label for=\"district\">Quận, huyện<span>*</span></label> <select\r\n");
      out.write("							id=\"district\" name=\"district\" required>\r\n");
      out.write("							<option value=\"\">Chọn quận huyện</option>\r\n");
      out.write("							Thêm các tỉnh thành khác ở đây\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group-sub\">\r\n");
      out.write("						<label for=\"ward\">Phường, xã<span>*</span></label> <select\r\n");
      out.write("							id=\"ward\" name=\"ward\" required>\r\n");
      out.write("							<option value=\"\">Chọn phường xã</option>\r\n");
      out.write("							Thêm các tỉnh thành khác ở đây\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div> -->\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("					<label for=\"phone\">Số điện thoại <span>*</span></label> <input\r\n");
      out.write("						type=\"text\" id=\"phone\" name=\"phone\"\r\n");
      out.write("						");
      out.write(' ');
      out.write(' ');
if(phone==null){ 
      out.write("value=\"\" ");
}else{ 
      out.write("value=\"");
      out.print(phone);
      out.write('"');
      out.write(' ');
} 
      out.write(" required>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<label for=\"email\">Địa chỉ email <span>*</span></label> <input\r\n");
      out.write("						type=\"email\" id=\"email\" name=\"email1\"\r\n");
      out.write("						value=\"");
      out.print(email);
      out.write("\" disabled>\r\n");
      out.write("						<input type=\"hidden\" name =\"email\"  value=\"");
      out.print(email);
      out.write("\" >\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<label for=\"address\">Địa chỉ<span>*</span></label> <input\r\n");
      out.write("						type=\"text\" id=\"address\" name=\"address\"\r\n");
      out.write("						 ");
if(address==null){ 
      out.write("value=\"\" ");
}else{ 
      out.write("value=\"");
      out.print(address);
      out.write('"');
      out.write(' ');
} 
      out.write(" required>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"order-summary\">\r\n");
      out.write("				<h2>ĐƠN HÀNG CỦA BẠN</h2>\r\n");
      out.write("				<table id=\"order-summary-table\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>SẢN PHẨM</th>\r\n");
      out.write("						<th>TẠM TÍNH</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

					for (CartDTO c : cartList) {
					
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td class=\"left\">");
      out.print(c.getProductGroupName());
      out.write(' ');
      out.print(c.getSize());
      out.write(" x <span\r\n");
      out.write("							class=\"quantity\">");
      out.print(c.getQuantity());
      out.write("</span></td>\r\n");
      out.write("						<td><span class=\"price\" data-price=\"");
      out.print(c.getPrice());
      out.write("\"></span>\r\n");
      out.write("						<input type=\"hidden\" name=\"productID\" value=\"");
      out.print(c.getProductID());
      out.write("\"></td>\r\n");
      out.write("						<input type=\"hidden\" name=\"quantity\" value=\"");
      out.print(c.getQuantity());
      out.write("\">\r\n");
      out.write("						<input type=\"hidden\" name=\"price\" value=\"");
      out.print(c.getPrice());
      out.write("\">\r\n");
      out.write("					</tr>\r\n");
      out.write("					");

					}
					
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>Tổng tạm tính</th>\r\n");
      out.write("						<td><span id=\"subtotal\"></span></td>\r\n");
      out.write("						<input type=\"hidden\" name=\"subTotal\" id=\"hiddenSubtotal\">\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>Vận chuyển\r\n");
      out.write("						</th>\r\n");
      out.write("						<td>Giao hàng miễn phí</td>\r\n");
      out.write("						<input type=\"hidden\" name=\"shipping\" value=\"0\">\r\n");
      out.write("					</tr>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>Tổng thanh toán</th>\r\n");
      out.write("						<td><span id=\"grandtotal\"></span></td>\r\n");
      out.write("						<input type=\"hidden\" name=\"grandTotal\" id=\"hiddenGrandtotal\">\r\n");
      out.write("					</tr>\r\n");
      out.write("				</table>\r\n");
      out.write("				<div class=\"payment-method\">\r\n");
      out.write("					<h3>Phương thức thanh toán</h3>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<input type=\"radio\" id=\"cod\" name=\"method\" value=\"cod\" checked>\r\n");
      out.write("						<label for=\"cod\">Thanh toán khi nhận hàng</label>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<input type=\"radio\" id=\"paypal\" name=\"method\" value=\"paypal\">\r\n");
      out.write("						<label for=\"paypal\">Thanh toán qua Paypal</label>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- <a href=\"#\" class=\"order-btn\">Đặt hàng</a> -->\r\n");
      out.write("				<input type=\"hidden\" name=\"grandTotal\" value=\"777\">\r\n");
      out.write("				<button type=\"submit\" class=\"order-btn\">Đặt hàng</button>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footer-container\">\r\n");
      out.write("			<div class=\"footer-section\">\r\n");
      out.write("				<h3>Về chúng tôi</h3>\r\n");
      out.write("				<p>COSMETIC SHOP chuyên cung cấp các sản phẩm chăm sóc da uy tín\r\n");
      out.write("					và chất lượng.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"footer-section\">\r\n");
      out.write("				<h3>Liên hệ</h3>\r\n");
      out.write("				<p>Email: 123@example.com</p>\r\n");
      out.write("				<p>Điện thoại: 0123-456-789</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"footer-section\">\r\n");
      out.write("				<h3>Kết nối với chúng tôi</h3>\r\n");
      out.write("				<p>\r\n");
      out.write("					<a href=\"#\"><i class=\"fa-brands fa-facebook\"></i></a> <a href=\"#\"><i\r\n");
      out.write("						class=\"fa-brands fa-twitter\"></i></a> <a href=\"#\"><i\r\n");
      out.write("						class=\"fa-brands fa-instagram\"></i></a>\r\n");
      out.write("				</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		var citis = document.getElementById(\"city\");\r\n");
      out.write("		var districts = document.getElementById(\"district\");\r\n");
      out.write("		var wards = document.getElementById(\"ward\");\r\n");
      out.write("		var Parameter = {\r\n");
      out.write("		  url: \"https://raw.githubusercontent.com/kenzouno1/DiaGioiHanhChinhVN/master/data.json\", \r\n");
      out.write("		  method: \"GET\", \r\n");
      out.write("		  responseType: \"application/json\", \r\n");
      out.write("		};\r\n");
      out.write("		var promise = axios(Parameter);\r\n");
      out.write("		promise.then(function (result) {\r\n");
      out.write("		  renderCity(result.data);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		function renderCity(data) {\r\n");
      out.write("		  for (const x of data) {\r\n");
      out.write("		    citis.options[citis.options.length] = new Option(x.Name, x.Id);\r\n");
      out.write("		  }\r\n");
      out.write("		  citis.onchange = function () {\r\n");
      out.write("		    district.length = 1;\r\n");
      out.write("		    ward.length = 1;\r\n");
      out.write("		    if(this.value != \"\"){\r\n");
      out.write("		      const result = data.filter(n => n.Id === this.value);\r\n");
      out.write("		\r\n");
      out.write("		      for (const k of result[0].Districts) {\r\n");
      out.write("		        district.options[district.options.length] = new Option(k.Name, k.Id);\r\n");
      out.write("		      }\r\n");
      out.write("		    }\r\n");
      out.write("		  };\r\n");
      out.write("		  district.onchange = function () {\r\n");
      out.write("		    ward.length = 1;\r\n");
      out.write("		    const dataCity = data.filter((n) => n.Id === citis.value);\r\n");
      out.write("		    if (this.value != \"\") {\r\n");
      out.write("		      const dataWards = dataCity[0].Districts.filter(n => n.Id === this.value)[0].Wards;\r\n");
      out.write("		\r\n");
      out.write("		      for (const w of dataWards) {\r\n");
      out.write("		        wards.options[wards.options.length] = new Option(w.Name, w.Id);\r\n");
      out.write("		      }\r\n");
      out.write("		    }\r\n");
      out.write("		  };\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("		    const prices = document.querySelectorAll('.price');\r\n");
      out.write("		    const quantities = document.querySelectorAll('.quantity');\r\n");
      out.write("		    const subtotalElem = document.getElementById('subtotal');\r\n");
      out.write("		    const grandtotalElem = document.getElementById('grandtotal');\r\n");
      out.write("		    const hiddenSubtotal = document.getElementById('hiddenSubtotal');\r\n");
      out.write("		    const hiddenGrandtotal = document.getElementById('hiddenGrandtotal');\r\n");
      out.write("		    const shippingCost = 0;\r\n");
      out.write("		    const discount = 0;\r\n");
      out.write("\r\n");
      out.write("		    let subtotal = 0;\r\n");
      out.write("\r\n");
      out.write("		    prices.forEach((priceElem, index) => {\r\n");
      out.write("		        const price = parseFloat(priceElem.getAttribute('data-price'));\r\n");
      out.write("		        const quantity = parseInt(quantities[index].innerText);\r\n");
      out.write("		        const totalPrice = price * quantity;\r\n");
      out.write("\r\n");
      out.write("		        priceElem.innerText = totalPrice.toLocaleString('vi-VN', { style: 'currency', currency: 'VND' });\r\n");
      out.write("		        subtotal += totalPrice;\r\n");
      out.write("		    });\r\n");
      out.write("\r\n");
      out.write("		    subtotalElem.innerText = subtotal.toLocaleString('vi-VN', { style: 'currency', currency: 'VND' });\r\n");
      out.write("		    const grandtotal = subtotal + shippingCost - discount;\r\n");
      out.write("		    grandtotalElem.innerText = grandtotal.toLocaleString('vi-VN', { style: 'currency', currency: 'VND' });\r\n");
      out.write("\r\n");
      out.write("		    hiddenSubtotal.value = subtotal;\r\n");
      out.write("		    hiddenGrandtotal.value = grandtotal;\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
