/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2024-06-26 15:34:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import common.StringCommon;
import model.dto.OrderDTO;
import java.util.ArrayList;

public final class order_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.dto.OrderDTO");
    _jspx_imports_classes.add("common.StringCommon");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Trang Thanh Toán</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    .body-infor {\r\n");
      out.write("        width: 85%;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        /* margin: 20px; */\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        width: 85%;\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        min-height: 500px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-infor {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .infor-form {\r\n");
      out.write("        width: 30%;\r\n");
      out.write("        padding: 0 20px 20px 20px;\r\n");
      out.write("        flex: 1 1 30%;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        min-width: 300px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .infor-form input {\r\n");
      out.write("        min-width: 120px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .infor-summary {\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        width: 65%;\r\n");
      out.write("        flex: 1 1 65%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        border: #ccc solid 1px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-infor h2 {\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        margin-top: 0;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .container-infor h3 {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .container-infor label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        margin-left: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-infor input[type=\"text\"],\r\n");
      out.write("    .container-infor input[type=\"email\"] {\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        margin-left: 20px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .infor-btn {\r\n");
      out.write("        background-color: #333;\r\n");
      out.write("        padding: 12px 24px;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        text-decoration: none\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .infor-btn:hover {\r\n");
      out.write("        background-color: #000;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar-infor {\r\n");
      out.write("        float: left;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background-color: #f1f1f1;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar-infor-a {\r\n");
      out.write("        display: block;\r\n");
      out.write("        color: black;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar-infor-a:hover {\r\n");
      out.write("        background-color: #ddd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .sidebar-infor-a-active {\r\n");
      out.write("\r\n");
      out.write("        background-color: #ccc;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .button-central {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .infor-summary .order-table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .infor-summary .order-table th {\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        border-bottom: #ccc solid 1px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        font-family: Proxima, sans-serif !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .infor-summary .order-table td {\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        font-family: Proxima, sans-serif !important;\r\n");
      out.write("    }\r\n");
      out.write("    .central{\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .href-a{\r\n");
      out.write("    	color: blue;\r\n");
      out.write("    	text-decoration:none;\r\n");
      out.write("    }\r\n");
      out.write("    .href-a:hover{\r\n");
      out.write("    	text-decoration:underline;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("        <div class=\"header-left\">\r\n");
      out.write("            <img src=\"logo.jpg\" alt=\"Logo\" class=\"logo\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-center\">\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"ShowHomeServlet\">Trang chủ</a></li>\r\n");
      out.write("                    <li><a href=\"ShowProductListServlet\">Sản phẩm</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Thương hiệu</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div class=\"search-bar\">\r\n");
      out.write("                <input type=\"text\" class=\"search-input\" placeholder=\"Tìm kiếm...\">\r\n");
      out.write("\r\n");
      out.write("                <button><i class=\"fa-solid fa-magnifying-glass\"></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-right\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart\">\r\n");
      out.write("                <a href=\"ShowCartServlet\"><i class=\"fa-solid fa-cart-shopping\"></i></a>\r\n");
      out.write("             <!--    <p>Giỏ hàng</p> -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("   			");
 if (session.getAttribute("accountInfor") == null) {
      out.write("		\r\n");
      out.write("	           <div class=\"profile-dropdown account\">\r\n");
      out.write("	                <a href=\"login.jsp\" title=\"Đăng nhập\"><i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("	           			<!--      <p>Tài khoản</p> -->\r\n");
      out.write("           	   </div>\r\n");
      out.write("	           ");
} else { 
      out.write("\r\n");
      out.write("           \r\n");
      out.write("               <div class=\"profile-dropdown \">\r\n");
      out.write("	                <a href=\"#\" title=\"Tài khoản\"><i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("	           			<!--<p>Tài khoản</p> -->\r\n");
      out.write("	                <div class=\"profile-dropdown-content\">\r\n");
      out.write("	                    <a href=\"ShowInforServlet\"><i class=\"fa-regular fa-user\"></i>Thông tin tài khoản</a>\r\n");
      out.write("	                    <a href=\"ShowOrderServlet\"><i class=\"fa-solid fa-list-check\"></i>Quản lý đơn hàng</a>\r\n");
      out.write("	                    <a href=\"LogoutServlet\"><i class=\"fa-solid fa-arrow-right-from-bracket\"></i>Đăng xuất</a>\r\n");
      out.write("	                </div>\r\n");
      out.write("            	</div>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"body-infor\">\r\n");
      out.write("        <div class=\"central\">\r\n");
      out.write("            <h2>THÔNG TIN TÀI KHOẢN</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-infor\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"infor-form\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"sidebar-infor\">\r\n");
      out.write("                    <a href=\"ShowInforServlet\" class=\"sidebar-infor-a \" href=\"#\">Thông tin tài khoản</a>\r\n");
      out.write("                    <a href=\"ShowOrderServlet\" class=\"sidebar-infor-a sidebar-infor-a-active\">Quản lý đơn hàng</a>\r\n");
      out.write(" <!--                    <a class=\"sidebar-infor-a\">Địa chỉ thanh toán và giao hàng</a> -->\r\n");
      out.write("                    <a  href=\"changePassword.jsp\" class=\"sidebar-infor-a\">Thay đổi mật khẩu</a>\r\n");
      out.write("                    <a href=\"LogoutServlet\" class=\"sidebar-infor-a\"><i class=\"fa-solid fa-arrow-right-from-bracket\"></i> Đăng xuất</a>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"infor-summary\">\r\n");
      out.write("            <h2>Quản Lý Đơn Hàng</h2>\r\n");
      out.write("            ");
 
ArrayList<OrderDTO> orderList = (ArrayList<OrderDTO>) request.getAttribute("orderList");
            if (orderList == null || orderList.isEmpty()) {
      out.write("\r\n");
      out.write("            <p class=\"central\">Bạn chưa có đơn hàng nào.</p>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("                 <table class=\"order-table\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>Đơn hàng</th>\r\n");
      out.write("                            <th>Thời gian</th>\r\n");
      out.write("                            <th>Trạng thái</th>\r\n");
      out.write("                            <th>Tổng tiền</th>\r\n");
      out.write("                            <th>Chi tiết</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                    ");
for(OrderDTO o : orderList) { 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <div class=\"product-name-td\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <p>");
      out.print(o.getOrderID() );
      out.write("</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                            ");
      out.print(StringCommon.validateDateTime(o.getOrderDate()) );
      out.write("\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                             ");
if("cho".equals(o.getStatus())){
      out.write("\r\n");
      out.write("				            <span class=\"order-status-cho\">Chờ xác nhận</span>\r\n");
      out.write("				            ");
}
      out.write("\r\n");
      out.write("				            ");
if("giao".equals(o.getStatus())){
      out.write("\r\n");
      out.write("				            <span class=\"order-status-giao\">Đang giao</span>\r\n");
      out.write("				            ");
}
      out.write("\r\n");
      out.write("				            ");
if("xong".equals(o.getStatus())){
      out.write("\r\n");
      out.write("				            <span class=\"order-status-xong\">Hoàn thành</span>\r\n");
      out.write("				            ");
}
      out.write("\r\n");
      out.write("                            </td>\r\n");
      out.write("            				<td class=\"bold\">");
      out.print(StringCommon.formatCurrency(o.getGrandTotal()));
      out.write("</td>\r\n");
      out.write("           					 <td><a class=\"href-a\" href='ShowOrderDetailServlet?orderID=");
      out.print(o.getOrderID());
      out.write("'>Xem chi tiết</a></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!-- Thêm các dòng sản phẩm khác ở đây -->\r\n");
      out.write("            </tbody>\r\n");
      out.write("            </table> \r\n");
      out.write(" ");
} 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"footer-container\">\r\n");
      out.write("            <div class=\"footer-section\">\r\n");
      out.write("                <h3>Về chúng tôi</h3>\r\n");
      out.write("                <p>COSMETIC SHOP chuyên cung cấp các sản phẩm chăm sóc da uy tín và chất lượng.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-section\">\r\n");
      out.write("                <h3>Liên hệ</h3>\r\n");
      out.write("                <p>Email: 123@example.com</p>\r\n");
      out.write("                <p>Điện thoại: 0123-456-789</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-section\">\r\n");
      out.write("                <h3>Kết nối với chúng tôi</h3>\r\n");
      out.write("                <p>\r\n");
      out.write("                    <a href=\"#\"><i class=\"fa-brands fa-facebook\"></i></a>\r\n");
      out.write("                    <a href=\"#\"><i class=\"fa-brands fa-twitter\"></i></a>\r\n");
      out.write("                    <a href=\"#\"><i class=\"fa-brands fa-instagram\"></i></a>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
