/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2024-06-27 04:39:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import common.StringCommon;
import java.util.ArrayList;
import model.dto.OrderDTO;
import model.dto.OrderDetailDTO;

public final class review_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.dto.OrderDTO");
    _jspx_imports_classes.add("common.StringCommon");
    _jspx_imports_classes.add("model.dto.OrderDetailDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Trang Thanh Toán</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    .finish-order {\r\n");
      out.write("        width: 85%;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        margin: 20px;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        width: 85%;\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        margin-top: 80px;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-finish-order {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: row;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        max-width: 1200px;\r\n");
      out.write("        gap: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .checkout-form input {\r\n");
      out.write("        min-width: 120px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-inline {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        /* Thêm display flex cho inline */\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        /* Canh chỉnh các thành phần trên cùng một hàng */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-inline label {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("        /* Để tạo khoảng cách giữa label và input */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .finish-order-summary1 {\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        border: #ccc solid 1px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .finish-order-summary {\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        border: black solid 1px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-finish-order1 h2 {\r\n");
      out.write("        font-size: 24px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        margin-top: 0;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .container-finish-order h3 {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        margin-bottom: 10px;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .form-inline {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        /* Thêm display flex cho inline */\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        /* Canh chỉnh các thành phần trên cùng một hàng */\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-inline label {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("        /* Để tạo khoảng cách giữa label và input */\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group {\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-group-sub {\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("        margin-right: 31px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-finish-order label {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-finish-order input[type=\"text\"],\r\n");
      out.write("    .container-finish-order input[type=\"email\"] {\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-finish-order input[type=\"checkbox\"],\r\n");
      out.write("    .container-finish-order input[type=\"radio\"] {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container-finish-order select {\r\n");
      out.write("        padding: 10px 0 10px 5px;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .finish-order-summary1 table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .finish-order-summary1 th {\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border-bottom: 1px solid #ddd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .finish-order-summary1 td {\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        border-bottom: 1px solid #ddd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .end-td {\r\n");
      out.write("        text-align: right !important;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* .finish-order-summary th {\r\n");
      out.write("        background-color: #f9f9f9;\r\n");
      out.write("    } */\r\n");
      out.write("\r\n");
      out.write("    .payment-method {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .payment-method .form-group {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .progress-bar {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        /* align-items: center; */\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        margin: 40px 40px 40px 40px;\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .progress-bar .step {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: #999;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .progress-bar .step.active .icon {\r\n");
      out.write("        color: #000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .progress-bar .step .icon {\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("        color: #ccc;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .progress-bar .line {\r\n");
      out.write("        margin-top: 15px;\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        height: 1px;\r\n");
      out.write("        background-color: #ccc;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .progress-bar .line.active {\r\n");
      out.write("        background-color: #000;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .progress-bar .step.active {\r\n");
      out.write("        color: #000;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .order-btn {\r\n");
      out.write("        background-color: #333;\r\n");
      out.write("        padding: 12px 24px;\r\n");
      out.write("        margin: 30px;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        font-size: 19px;\r\n");
      out.write("        text-decoration: none\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .order-btn:hover {\r\n");
      out.write("        background-color: #000;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .checkout-button{\r\n");
      out.write("    background-color: #333;\r\n");
      out.write("        padding: 12px 24px;\r\n");
      out.write("        margin: 30px;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 3px;\r\n");
      out.write("        font-size: 19px;\r\n");
      out.write("        text-decoration: none\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .central{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");

    OrderDTO order = (OrderDTO) request.getAttribute("order");
    if (order != null) {
        
    } else {
        out.println("Không có sản phẩm!");
    }

      out.write("\r\n");
      out.write("\r\n");

    ArrayList<OrderDetailDTO> orderDetail = (ArrayList<OrderDetailDTO>) request.getAttribute("orderDetail");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("        <div class=\"header-left\">\r\n");
      out.write("            <img src=\"logo.jpg\" alt=\"Logo\" class=\"logo\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-center\">\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"ShowHomeServlet\">Trang chủ</a></li>\r\n");
      out.write("                    <li><a href=\"ShowProductListServlet\">Sản phẩm</a></li>\r\n");
      out.write("                    <li><a href=\"#\">Thương hiệu</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div class=\"search-bar\">\r\n");
      out.write("                <input type=\"text\" class=\"search-input\" placeholder=\"Tìm kiếm...\">\r\n");
      out.write("\r\n");
      out.write("                <button><i class=\"fa-solid fa-magnifying-glass\"></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-right\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart\">\r\n");
      out.write("                <a href=\"ShowCartServlet\"><i class=\"fa-solid fa-cart-shopping\"></i></a>\r\n");
      out.write("             <!--    <p>Giỏ hàng</p> -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("   			");
 if (session.getAttribute("accountInfor") == null) {
      out.write("		\r\n");
      out.write("	           <div class=\"profile-dropdown account\">\r\n");
      out.write("	                <a href=\"login.jsp\" title=\"Đăng nhập\"><i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("	           			<!--      <p>Tài khoản</p> -->\r\n");
      out.write("           	   </div>\r\n");
      out.write("	           ");
} else { 
      out.write("\r\n");
      out.write("           \r\n");
      out.write("               <div class=\"profile-dropdown account\">\r\n");
      out.write("	                <a href=\"#\" title=\"Tài khoản\"><i class=\"fa-solid fa-user\"></i></a>\r\n");
      out.write("	           			<!--<p>Tài khoản</p> -->\r\n");
      out.write("	                <div class=\"profile-dropdown-content\">\r\n");
      out.write("	                    <a href=\"ShowInforServlet\"><i class=\"fa-regular fa-user\"></i>Thông tin tài khoản</a>\r\n");
      out.write("	                    <a href=\"ShowOrderServlet\"><i class=\"fa-solid fa-list-check\"></i>Quản lý đơn hàng</a>\r\n");
      out.write("	                    <a href=\"LogoutServlet\"><i class=\"fa-solid fa-arrow-right-from-bracket\"></i>Đăng xuất</a>\r\n");
      out.write("	                </div>\r\n");
      out.write("            	</div>\r\n");
      out.write("                ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"progress-bar\">\r\n");
      out.write("            <div class=\"step active\">\r\n");
      out.write("                <div class=\"icon\"><i class=\"fa-solid fa-cart-shopping\"></i></div>\r\n");
      out.write("                <div class=\"text\">Giỏ hàng</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"line active\"></div>\r\n");
      out.write("            <div class=\"step active\">\r\n");
      out.write("                <div class=\"icon\"><i class=\"fa-regular fa-credit-card\"></i></i></div>\r\n");
      out.write("                <div class=\"text\">Thanh toán</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"line\"></div>\r\n");
      out.write("            <div class=\"step\">\r\n");
      out.write("                <div class=\"icon\"><i class=\"fa-regular fa-circle-check\"></i></div>\r\n");
      out.write("                <div class=\"text\">Hoàn thành</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-finish-order\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"finish-order-summary\">\r\n");
      out.write("                <h2>THANH TOÁN</h2>\r\n");
      out.write("                \r\n");
      out.write("                <!--  <h1>Please Review Before Paying</h1> -->\r\n");
      out.write("    <form action=\"execute_payment\" method=\"post\">\r\n");
      out.write("    <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td colspan=\"2\"><b>Thông tin thanh toán:</b></td>\r\n");
      out.write("            <td>\r\n");
      out.write("                <input type=\"hidden\" name=\"paymentId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.paymentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                <input type=\"hidden\" name=\"PayerID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.PayerID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                \r\n");
      out.write("            </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <!-- <tr>\r\n");
      out.write("            <td colspan=\"2\"><b>Payer Information:</b></td>\r\n");
      out.write("        </tr> -->\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Tên tài khoản:</td>\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payer.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payer.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Email:</td>\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${payer.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Tổng thanh toán:</td>\r\n");
      out.write("           ");
      out.write("\r\n");
      out.write("            <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${transaction.amount.total}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" USD</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("        </tr> \r\n");
      out.write("        <tr>\r\n");
      out.write("        <td colspan=\"2\"><b>Thông tin nhận hàng:</b></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Tên người mua:</td>\r\n");
      out.write("            <td>");
      out.print(order.getCustomerName() );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Địa chỉ:</td>\r\n");
      out.write("            <td>");
      out.print(order.getAddress() );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>Số điện thoại:</td>\r\n");
      out.write("            <td>");
      out.print(order.getPhone() );
      out.write("</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"finish-order-summary1\">\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>SẢN PHẨM</th>\r\n");
      out.write("                        <th>Đơn giá</th>\r\n");
      out.write("                        <th>Số lượng</th>\r\n");
      out.write("                        <th class=\"end-td\">Tạm tính</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");
for(OrderDetailDTO o : orderDetail) { 
      out.write("\r\n");
      out.write("                    <input type=\"hidden\" name=\"orderID\" value=\"");
      out.print(o.getOrderID());
      out.write("\"/>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td>");
      out.print(o.getProductName() );
      out.write(' ');
      out.print(o.getSize() );
      out.write(" \r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td>");
      out.print(StringCommon.formatCurrency(o.getPrice()));
      out.write("</td>\r\n");
      out.write("                        <td>");
      out.print(o.getQuantity());
      out.write("</td>\r\n");
      out.write("                        <td class=\"end-td\">");
      out.print(StringCommon.formatCurrency(o.getPrice() * o.getQuantity()) );
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");
} 
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Tổng tạm tính</th>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td class=\"end-td\">");
      out.print(StringCommon.formatCurrency(order.getGrandTotal()) );
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Vận chuyển</th>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td class=\"end-td\">Giao hàng miễn phí</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Phương thức thanh toán</th>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        ");
if("paypal".equals(order.getPayment())) { 
      out.write("\r\n");
      out.write("                        <td class=\"end-td\">Thanh toán qua Paypal</td>\r\n");
      out.write("                        ");
 } else { 
      out.write("\r\n");
      out.write("                        <td class=\"end-td\">Thanh toán khi nhận hàng </td>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>Tổng thanh toán</th>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td></td>\r\n");
      out.write("                        <td class=\"end-td\">");
      out.print(StringCommon.formatCurrency(order.getGrandTotal()));
      out.write("</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("    <div class=\"central\">\r\n");
      out.write("                    <button class=\"checkout-button\" type=\"submit\" >Thanh toán</button></div>\r\n");
      out.write("    </form>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
